modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = "https://github.com/matthewperiut/clay-soldiers/"
license = "MIT"

[[mods]]
modId = "clay"
version = "${version}"
displayName = "Clay Soldiers"
authors = "Slainlite"
description = '''
This adds clay soldiers that attack for you!
'''
#logoFile = "icon.png"

[[dependencies.clay]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.clay]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.clay]]
modId = "geckolib3"
mandatory = true
versionRange = "[3.0.35,)"
ordering = "NONE"
side = "BOTH"
